# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.boot_timeout = 600

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "3072"
  end
  #configure provisioners on machines
  config.vm.provision :docker 
  
  #Server ci-server
  config.vm.define "ci-server" do |ciserver|
    ciserver.vm.network "private_network", ip: '192.168.56.60'
    ciserver.vm.hostname = "ciserver"
    ciserver.vm.provision :file, source: "../docker/docker-compose.ci.yml", destination: "docker-compose.yml"
    ciserver.vm.provision :docker_compose, yml:"/home/vagrant/docker-compose.yml", run: "always"
    ciserver.vm.provision :shell, inline:"sudo chmod 777 /var/run/docker.sock"
  end
  #Server server-2
  config.vm.define "server-2" do |server2|
    server2.vm.network "private_network", ip: '192.168.56.61'
    server2.vm.hostname = "server-2"
  end

end
